#端口号
server:
  port: 8006

#服务别名——注册到zookeeper注册中心的名称
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: localhost  #用linux的ip地址（consul在本机就填localhost）
      port: 8500
      discovery:
        service-name: ${spring.application.name}
