#端口号
server:
  port: 82

spring:
  application:
    name: consul-consumer-payment
  cloud:
    consul:
      host: localhost  #用linux的ip地址（consul在本机就填localhost）
      port: 8500
      discovery:
        service-name: ${spring.application.name}
